# Generated by Django 4.1.5 on 2023-01-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_director_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
