# Generated by Django 4.1.5 on 2023-01-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_alter_director_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='fallecimiento',
            field=models.DateField(blank=True),
        ),
    ]
